### ISSUE TITLE
請問 searchContent 怎麼支持分頁

### ISSUE THREAD

**Issue by FongMi** [UndCover/Pyramid#1]
我多加一個 pg 參數在最後一個，似乎會影響原有的爬蟲，不像 js 會自動處理。

**Comment by UndCover** [comment]
添加参数 会涉及比较多的地方，可以尝试以下步骤
1. python/src/main/java/com/undcover/freedom/pyramid/PythonSpider.java -> line 231 添加相关的参数
2. python/src/python/base/spider.py -> line 34 添加参数 
3. python/src/python/app.py -> line 115 添加参数 , line 116 添加参数
4. 爬虫插件-> func searchContent 添加参数

鉴于添加参数会对现存的插件有影响，建议在爬虫插件中添加对应的版本参数来支持新旧插件

**Comment by FongMi** [comment]
好的，那我還是朝向多一個 func 處理，例如 searchContentPg。
